[build]
  base = ""
  publish = "dist"
  command = "VITE_FIREBASE_PROJECT_ID=erp-for-tsa VITE_FIREBASE_API_KEY=AIzaSyB8Z4GdoLZsBW6bfmAh_BSTftpTRUXPZMw VITE_FIREBASE_AUTH_DOMAIN=erp-for-tsa.firebaseapp.com VITE_FIREBASE_DATABASE_URL=https://erp-for-tsa-default-rtdb.firebaseio.com VITE_FIREBASE_STORAGE_BUCKET=erp-for-tsa.firebasestorage.app VITE_FIREBASE_MESSAGING_SENDER_ID=271232983905 VITE_FIREBASE_APP_ID=1:271232983905:web:7d06c8f5ec269824759b20 VITE_FIREBASE_MEASUREMENT_ID=G-6CYWPS4N0G npm run build:skip-check"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "text/html; charset=utf-8"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

# Environment variables for different contexts
[context.production.environment]
  NODE_ENV = "production"
  VITE_FIREBASE_API_KEY = "$VITE_FIREBASE_API_KEY"
  VITE_FIREBASE_AUTH_DOMAIN = "$VITE_FIREBASE_AUTH_DOMAIN"
  VITE_FIREBASE_PROJECT_ID = "$VITE_FIREBASE_PROJECT_ID"
  VITE_FIREBASE_STORAGE_BUCKET = "$VITE_FIREBASE_STORAGE_BUCKET"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "$VITE_FIREBASE_MESSAGING_SENDER_ID"
  VITE_FIREBASE_APP_ID = "$VITE_FIREBASE_APP_ID"
  VITE_FIREBASE_MEASUREMENT_ID = "$VITE_FIREBASE_MEASUREMENT_ID"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Functions (if needed for serverless functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin configuration (temporarily disabled for deployment)
# [[plugins]]
#   package = "@netlify/plugin-sitemap"

# [[plugins]]
#   package = "netlify-plugin-lighthouse"
#   [plugins.inputs]
#     output_path = "reports/lighthouse"